last_change = 2025-06-05T16:00:38.185127Z
addr = 0x1c00
size = 0x107
name = "youstupidbitch"
type = "long long"
artifact_type = "Function"

[header]
name = "youstupidbitch"
addr = 0x1c00
type = "long long"

[header.args]
