last_change = 2025-06-05T15:06:54.451108Z
addr = 0x13bc
size = 0x159
name = "somethingsomething"
artifact_type = "Function"

[header]
last_change = 2025-06-05T15:06:54.451108Z
name = "somethingsomething"
addr = 0x13bc

[header.args]
