last_change = 2025-06-05T15:56:24.430280Z
addr = 0x13bc
size = 0x159
name = "somethingsomething"
type = "long long"
artifact_type = "Function"

[header]
name = "somethingsomething"
addr = 0x13bc
type = "long long"

[header.args]
